# Generated by Django 5.0.6 on 2024-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
