# Generated by Django 5.0.6 on 2024-07-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_baner_contact_house_info_roomimg_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTATE_AGENTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGENT_name', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
