# Generated by Django 5.0.6 on 2024-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_estate_agents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGENT_name', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('ss', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ESTATE_AGENTS',
        ),
    ]
