# Generated by Django 5.0.6 on 2024-07-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_estata_delete_estate_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estata',
            name='ss',
        ),
    ]
