# Generated by Django 5.0.6 on 2024-07-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_agent_delete_iormat'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('money', models.IntegerField(default=24000)),
                ('text', models.TextField()),
            ],
        ),
    ]
