# Generated by Django 5.0.6 on 2024-07-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_service_body_home_imgs_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimg',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
