# Generated by Django 5.0.6 on 2024-07-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_roomimg_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
