# Generated by Django 5.0.6 on 2024-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_service_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contct_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adress', models.TextField()),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
